import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const __dirname = dirname(fileURLToPath(import.meta.url));

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is regenerated by Next itself on every build — never
    // hand-edited, so it's excluded rather than "fixed" (Next would just
    // reintroduce the same pattern).
    ignores: ['.next/**', 'node_modules/**', 'next-env.d.ts'],
  },
  {
    linterOptions: {
      // M1-Batch3 pages defensively added `eslint-disable-next-line
      // react/no-array-index-key` at dozens of call sites, anticipating a
      // rule that isn't actually part of next/core-web-vitals's active set
      // (this is the very first time this codebase has run any linter) —
      // now flagged as "unused directive." Harmless and widespread across
      // already-shipped batches; a config-level opt-out here is the
      // appropriate fix, not a 20+ file cleanup pass (see CLAUDE.md: "don't
      // modify previous batches unless fixing a critical issue").
      reportUnusedDisableDirectives: 'off',
    },
  },
];

export default eslintConfig;
